### PR TITLE
bump version to v1.2.1

### PR DESCRIPTION
**Pull request by valeriupredoi**
Hi @conda-forge/requirements-detector @jakirkham I am in the middle of Py311ing our package and we need prospector at latest, and prospector needs requirements-detector>=1.0.3, was wondering if I can help build a newer one here, hope you don't mind :beer: 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~[ ] Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #20
Closes #17
Closes #15
Closes #14

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by valeriupredoi** [comment]
adapting this since there is now a new and fully conda-forgeable version 1.2.1 https://pypi.org/project/requirements-detector/

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by valeriupredoi** [comment]
@zklaus heads up the new 1.2.1 version works beautifully for conda-forge-only deps, so you may want to let this through first then noarch it as in #19 - up to you and @jakirkham - this is ready, cheers to @carlio upstream for the very prompt release!

**Comment by valeriupredoi** [comment]
now that https://github.com/conda-forge/requirements-detector-feedstock/pull/19 has been merged I will have to tweak this to get in the noarch structure - unfortunately I'll have limited time next week, so by all means, if others want to do it - go ahead - maybe @jakirkham if you got a bit of time, worst case scenario I'll fix it first week of May :beer:

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by jakirkham** [comment]
@valeriupredoi, no worries

In general with these conflicts would only worry about fixing up `recipe/` content and (when relevant `conda-forge.yml` content). The rest of the files can easily be regenerated with a re-render. So just pushing those through with *some* conflict resolution is usually good enough to get to the point where re-rendering can be done

Went ahead and did this above. Though hope that helps simplify the steps in the future 🙂

Can you please look over and make sure things look ok (or fix them if not)? Thanks! 🙏

**Comment by valeriupredoi** [comment]
ace @jakirkham - cheers muchly for bringing in those noarch changes, all looks great to me, tests pass, and I reckon we have us a nice new and py311-supporting version! Many thanks for all the help here, mate :beer:

**Comment by jakirkham** [comment]
Great thanks for double checking and the much needed work to refresh things here! 🙏

**Comment by valeriupredoi** [comment]
Brilliant, cheers @jakirkham 🍺 On to prospector now, no rest for the wicked 😁 Flying to a conference today, will try sort out the prospector update from Heathrow, mate

**Pull request merged**
