### PR TITLE
Convert to noarch: python

### LINKED ISSUE #16: Convert to noarch
### Comment:

Can this package be converted to noarch? AFAICS that should be straightforward.

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #16 

This converts this feedstock to `noarch: python`.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Review by valeriupredoi — APPROVED** [review]
great to see this going @zklaus - note that I am approving w/o any maintainer rights though. There is one more roadblock in front of a nifty conda package update - the use of `poetry-semver` that is now archived and old, and it's not on conda-forge, but for that I opened https://github.com/landscapeio/requirements-detector/pull/44 :beer:

**Comment by jakirkham** [comment]
So how should we handle this? Merge #18 or #19 first?

**Comment by zklaus** [comment]
I personally would do this one (#19) first. Since this old version of `requirements-detector` seems to work without the complicated dependency, we get one more version for free and have a better separation of issues.

**Comment by valeriupredoi** [comment]
@jakirkham cheers for getting back to us, mate! I am with @zklaus on this one. I can merge the new noarch into #18 and we do a clean, noarch release of the latest version 👍

**Comment by jakirkham** [comment]
Thanks you both! 🙏

**Comment by valeriupredoi** [comment]
many thanks @jakirkham :beer:

**Pull request merged**
